project:
  type: website
  output-dir: C:/Users/lushg123.stu/Desktop/GIT/E-Portfolio

website:
  title: "Grace Lush"  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

